### ISSUE TITLE
用户绑定的验证方式

### ISSUE THREAD

**Issue by CCXXXI** [rabbitkiller-dev/message_bridge_rs#35]
现在是直接在群里发验证码，这样基本没有验证作用，可能改成私聊验证码？

**Comment by yefu24324** [comment]
验证作用分两步
①. 验证码, ②. 最后回复确认

①. 验证码为了确认两个账号关联
②. 最后确认是为了防止别人手快顶替了你

---

而且做私聊感觉太麻烦了
