### ISSUE TITLE
提供指令：绑定dc与qq用户

### ISSUE THREAD

**Issue by RogenDong** [rabbitkiller-dev/message_bridge_rs#4]

**Comment by WinstonSung** [comment]
Done in:
* 57d311ccdf6a873ba59b9bbbada79c0178fc09ed

**Comment by winstonsung** [comment]
Done in:
* 57d311ccdf6a873ba59b9bbbada79c0178fc09ed
* 5e1314a7c63bc6ff67c154daab1b0017938ae5b1
* e3ee198643fb01f4ca97539f903116fa25b31a3d
* 6852bc92c57722f1dd32912e29b59414230e437f
* 6976b82d0041976027821a17cb0012e60e1beb19
* 9a5c0184fb8b07efae7f14fca415673931ea07c7
* 5e526755c590b2534a99759d7eaa7ad1f3363120
* e3fe2779f8f34701a05cd55d5684149a25e8929d

**Comment by yefu24324** [comment]
@WinstonSung T.T 其实这个还没完成, 在bot提供指令还没完全想好处理方式

**Comment by winstonsung** [comment]
> @WinstonSung T.T 其实这个还没完成, 在bot提供指令还没完全想好处理方式

Reopen?
